
export function Esmeralda() {
    return (
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" xml:space="preserve">
            <image width="24" height="24" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACgBAMAAAB54XoeAAAABGdBTUEAALGPC/xhBQAAACBjSFJN AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEUAAAAAUwDb/+tB84QX 3WKv/c0AqiwALQAAlSmC9q0Aexj///92T9yEAAAAAXRSTlMAQObYZgAAAAFiS0dECx/XxMAAAAAH d ElNRQfoBhsCNBZy4YS5AAAAq0lEQVRo3u3YMQ2AMBBGYSxgAQtYwAIWsFALWMACKsn9Qy9pSgIl Ybi+N7XLtzW56zAQERH90lgJEBCwtCZrzi1WqwoIGA10a7Uc3CypyQIE7BYsrBr4TgUEjAuKWXJO y9otnQABAUvwsMScFiAgICAgYAt45Bz8NM4BAsYFtfjI0jgHCNg36KovOWdOV/kNv3OAgNHAW/Xd gwME7AFUqVKrBQgYFyQiInrcBYpGZUUSZ2OGAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDI0LTA2LTI3 VDAyOjUyOjIyKzAwOjAwJGBJMwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyNC0wNi0yN1QwMjo1Mjoy MiswMDowMFU98Y8AAAAASUVORK5CYII=" />
        </svg>
    )
}